name:                higlut
version:             0.1.0.0
github:              "willxujun/higlut"
license:             BSD3
author:              "Xu Jun"
maintainer:          "xu.jun@u.nus.edu"
copyright:           "Copyright (c) 2018 Xu Jun"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/willxujun/higlut#readme>

dependencies:
- base >= 4.7 && < 5
- GLUT
- sdl2
- sdl2-gfx
- sdl2-ttf
- text

library:
  source-dirs: src

executables:
  higlut-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - higlut

tests:
  higlut-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - higlut
